### ISSUE TITLE
云服务器部署问题

### ISSUE THREAD

**Issue by undolog** [UPCUnofficial/yqfkReport#4]
如果将py文件和shell脚本放到ECS上，是不是只需加个crontab定时任务即可？
(github action感觉缺了个反馈，想加个邮箱反馈机制)

**Comment by lx200916** [comment]
加个Crontab可以,但是还要对脚本做些修改.
1. Python和Shell的作用是相同的,选择一个运行就可以.但是注意要安装好依赖,Python(requests),Shell(jq).Python版本相对更稳定一点点.
2. 脚本利用了Github Actions的Secrets功能存储并传递你的用户名和密码来保证安全,所以你可能需要把Shell脚本中的${username}和${password}替换为你的用户名密码明文(或者在脚本运行前设置环境变量),Python脚本同理.
3. Github Actions也可以设置失败时(或运行时)邮件提醒,在Account settings-> Notifications部分.

**Comment by undolog** [comment]
> 加个Crontab可以,但是还要对脚本做些修改.
> 
> 1. Python和Shell的作用是相同的,选择一个运行就可以.但是注意要安装好依赖,Python(requests),Shell(jq).Python版本相对更稳定一点点.
> 2. 脚本利用了Github Actions的Secrets功能存储并传递你的用户名和密码来保证安全,所以你可能需要把Shell脚本中的${username}和${password}替换为你的用户名密码明文(或者在脚本运行前设置环境变量),Python脚本同理.
> 3. Github Actions也可以设置失败时(或运行时)邮件提醒,在Account settings-> Notifications部分.
学到了，谢谢博主
